#![cfg(feature = "rhai")]

use dioxuscut_cli::rhai_runtime::RhaiComposition;
use dioxuscut_composition::{Composition, NativeCompositionContext};
use dioxuscut_rasterizer::SceneNode;
use serde_json::json;

#[test]
fn test_rhai_svg_and_mermaid_integration() {
    let script = r##"
        fn render(context, props) {
            let scene = scene();
            
            // 1. Direct SVG markup
            scene.svg(`<svg width="400" height="200"><circle cx="100" cy="100" r="40" fill="#10b981"/></svg>`);
            
            // 2. Mermaid flowchart
            let mermaid_code = "graph LR; A[Producer] -->|frames| B[GPU_Rasterizer]; B --> C[Encoder]";
            scene.mermaid(mermaid_code);
            
            return scene;
        }
    "##;

    let comp =
        RhaiComposition::from_source("test_rhai_svg_mermaid", script).expect("compile script");
    let ctx = NativeCompositionContext {
        width: 1920,
        height: 1080,
        fps: 30.0,
        duration_in_frames: 30,
    };

    let prepared = comp.prepare(&json!({}), ctx).expect("prepare composition");
    let scene = prepared.render(0).expect("render frame 0");

    // Has SVG circle
    let has_circle = scene
        .nodes
        .iter()
        .any(|n| matches!(n, SceneNode::Circle { .. }));
    assert!(has_circle, "Expected Circle node from SVG");

    // Has Mermaid nodes (Producer, GPU_Rasterizer, Encoder)
    let rect_count = scene
        .nodes
        .iter()
        .filter(|n| matches!(n, SceneNode::Rect { .. }))
        .count();
    assert!(
        rect_count >= 3,
        "Expected at least 3 rect nodes from Mermaid graph"
    );
}

#[test]
fn test_rhai_d3_declarative_charts() {
    let script = r##"
        fn render(context, props) {
            let scene = scene();
            
            // D3 Line Chart
            scene.d3_line([10, 45, 80, 120, 95], #{
                width: 600,
                height: 300,
                title: "Revenue",
                stroke: "#3b82f6",
                curve: "monotone"
            });
            
            // D3 Bar Chart
            scene.d3_bar([["Mon", 30], ["Tue", 75], ["Wed", 50]], #{
                x: 700,
                y: 50,
                width: 500,
                height: 300,
                title: "Daily Views"
            });
            
            // D3 Donut Chart
            scene.d3_pie([["Rust", 70], ["Python", 20], ["JS", 10]], #{
                x: 1300,
                y: 50,
                width: 400,
                height: 400,
                donut: 0.5,
                title: "Tech Stack"
            });
            
            return scene;
        }
    "##;

    let comp = RhaiComposition::from_source("test_rhai_d3", script).expect("compile script");
    let ctx = NativeCompositionContext {
        width: 1920,
        height: 1080,
        fps: 30.0,
        duration_in_frames: 30,
    };

    let prepared = comp.prepare(&json!({}), ctx).expect("prepare composition");
    let scene = prepared.render(0).expect("render frame 0");

    assert!(!scene.nodes.is_empty(), "Scene should contain chart nodes");
}

#[test]
fn test_rhai_quickjs_d3_eval() {
    let script = r##"
        fn render(context, props) {
            let scene = scene();
            
            let js_chart = `
                const svg = d3.select("svg").attr("width", 400).attr("height", 200);
                const x = d3.scaleLinear().domain([0, 4]).range([20, 380]);
                const y = d3.scaleLinear().domain([0, 100]).range([180, 20]);
                const line = d3.line().x((d, i) => x(i)).y(d => y(d)).curve(d3.curveMonotoneX);
                svg.append("path")
                   .attr("d", line(data))
                   .attr("stroke", "#ec4899")
                   .attr("stroke-width", 4)
                   .attr("fill", "none");
                return svg.html();
            `;
            
            scene.d3_eval(js_chart, [20, 60, 40, 90, 85]);
            return scene;
        }
    "##;

    let comp =
        RhaiComposition::from_source("test_rhai_quickjs_d3", script).expect("compile script");
    let ctx = NativeCompositionContext {
        width: 1920,
        height: 1080,
        fps: 30.0,
        duration_in_frames: 30,
    };

    let prepared = comp.prepare(&json!({}), ctx).expect("prepare composition");
    let scene = prepared.render(0).expect("render frame 0");

    let has_path = scene
        .nodes
        .iter()
        .any(|n| matches!(n, SceneNode::Path { stroke, .. } if stroke.is_some()));
    assert!(has_path, "Expected Path node generated by QuickJS D3");
}
