[package]
name = "dioxuscut-studio-tauri"
version.workspace = true
edition.workspace = true
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
dioxuscut-composition = { workspace = true }
dioxuscut-rasterizer = { workspace = true }
dioxuscut-project = { workspace = true }

[features]
custom-protocol = ["tauri/custom-protocol"]
